all: align

align:
	g++ -I/home/yinshuo/usr/xmipp -I/home/yinshuo/usr/xmipp/libraries -I/home/yinshuo/us/xmipp/external Align.cpp -L/home/yinshuo/usr/xmipp/lib  -lXmippData -lXmippClassif -lXmippDimred -lXmippExternal -lXmippInterface -lXmippSqliteExt -lXmippParallel -lXmippRecons -lXmippJNI -ltiff -o align
